apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-e2e-app-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: tekton-e2e-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/emea-8-jiri-petnik-tekton-e2e-app
    - name: image-repo
      value: quay.io/jpetnik/tekton-e2e-app
  pipelineRef:
    name: tekton-e2e-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
